language: go

go:
    - 1.8
    - 1.9
    - tip

matrix:
  allow_failures:
    - go: tip

install:
    - go get -u github.com/golang/dep/cmd/dep && dep ensure

script:
    - go test -v $(go list ./... | grep -v /vendor/)
